// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission04.Models;

namespace Mission04.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission04.Models.MovieResponse", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentto")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("MovieResponse");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            category = "Action/Adventure",
                            director = "Kevin Reynolds",
                            edited = false,
                            lentto = "",
                            notes = "One of the best movies ever made",
                            rating = "PG-13",
                            title = "The Count of Monte Cristo",
                            year = 2002
                        },
                        new
                        {
                            MovieId = 2,
                            category = "Action/Adventure",
                            director = "Michael Curtis",
                            edited = false,
                            lentto = "",
                            notes = "One of the best movies ever made",
                            rating = "PG",
                            title = "The Adventure of Robin Hood",
                            year = 1938
                        },
                        new
                        {
                            MovieId = 3,
                            category = "Sci-Fi",
                            director = "Christopher Nolan",
                            edited = false,
                            lentto = "",
                            notes = "One of the best movies ever made",
                            rating = "PG-13",
                            title = "Inception",
                            year = 2010
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
